import {
  AlertCircle,
  ArrowDownRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bot,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Database,
  FileText,
  Gauge,
  LayoutDashboard,
  LoaderCircle,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  Send,
  Sparkles,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  UserRound,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

const icons = {
  alert: AlertCircle,
  arrowDown: ArrowDownRight,
  arrowLeft: ArrowLeftToLine,
  arrowRight: ArrowRight,
  arrowUp: ArrowUpRight,
  analytics: BarChart3,
  book: BookOpen,
  bot: Bot,
  check: Check,
  checkCircle: CheckCircle2,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  close: X,
  collapse: PanelLeftClose,
  database: Database,
  dashboard: LayoutDashboard,
  expand: PanelLeftOpen,
  file: FileText,
  gauge: Gauge,
  help: CircleHelp,
  loader: LoaderCircle,
  menu: Menu,
  refresh: RefreshCw,
  send: Send,
  spark: Sparkles,
  trash: Trash2,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  upload: Upload,
  user: UserRound,
  users: Users,
  xCircle: XCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export default function Icon({ name, size = 20, className = "" }: { name: IconName; size?: number; className?: string }) {
  const Component = icons[name];
  return <Component aria-hidden="true" className={className} size={size} strokeWidth={1.9} />;
}
